### ISSUE TITLE
[Meta] Update notebook extensions to reflect Jupyter 4.2

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/anaconda-nb-extensions#139]
Once Jupyter Notebook PR https://github.com/jupyter/notebook/pull/879 is merged we will need to update our extensions to use this new strategy.

* [X] review PR 879 and test with nb_conda quick migration #145
* [x] contribute to PR 879 for completion #146
* [x] create serverextension CLI mechanism (follow up of PR 879 discussion, needed for nb_conda) #147
* [x] migrate all our extension to the new mechanism to use the proposed mechanism #148
* [ ] Testing #141 and #142

Nice to have:
* [ ] Validate Anaconda Enterprise Notebooks (Wakari Enterprise) #149

**Comment by stephenakearns** [comment]
Hi @damianavila - I think this is in progress, but if not, please update pipeline as needed

**Comment by damianavila** [comment]
@stephenakearns this is actually a meta-issue with several tasks.
I added all the needed steps for completion.
I opened issues for each one of these tasks and size them there to avoid size duplication with this one.

**Comment by bollwyvl** [comment]
Here's nb_anacondacloud:
https://github.com/Anaconda-Platform/nb_anacondacloud/pull/21

**Comment by bollwyvl** [comment]
- [ ] https://github.com/Anaconda-Platform/nb_conda_kernels/pull/20

**Comment by bollwyvl** [comment]
- [ ] https://github.com/Anaconda-Platform/nb_conda/pull/12

**Comment by damianavila** [comment]
@bollwyvl I was refering this one: #148, the last message contains the list as well...

**Comment by damianavila** [comment]
Sorry about the mistake... this should be the meta including all the things at the very top.
